- name: checkout my dotfiles
  git:
    repo: https://github.com/bryutus/dotfiles.git
    dest: ~/.dotfiles

- name: create symbolic link
  file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items: "{{ dotfiles }}"

- name: add zsh
  shell: echo '/usr/local/bin/zsh' | sudo tee -a /etc/shells
  become: yes

- name: change login shell
  shell: chsh -s /usr/local/bin/zsh

