mas_applications:
  - { name: '1Password', id: 443987910 }
  - { name: 'Day One', id: 1055511498 }
  - { name: 'ReadKit', id: 588726889 }
  - { name: 'Pixelmator', id: 407963104 }
#  - { name: 'ForkLift', id: 412448059 }
#  - { name: 'PopClip', id: 445189367}
  - { name: 'Things', id: 407951449  }
#  - { name: 'iA Writer', id: 775737590 }

