- name: install homebrew
  shell: |
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: update homebrew
  homebrew:
    update_homebrew=yes

- name: add homebrew tap repository
  homebrew_tap:
    tap={{ item }}
    state=present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{ item.install_options | default('omit') }}
  with_items: "{{ homebrew_packages }}"

- name: install homebrew cask packages
  homebrew_cask: >
    name={{ item.name }}
    state={{ item.state | default('present') }}
  with_items: "{{ homebrew_cask_packages }}"

