# 起動音量の確認 nvram -p | grep SystemAudioVolume
- name: disable start up sound
  command: /usr/sbin/nvram SystemAudioVolume=%00
  become: yes

- name: Create directory to save screen capture
  file: >
    path=~/Documents/ScreenCapture
    state=directory

- name: load locate.plist and register service
  debug: msg="launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist"
  become: yes
  with_first_found:
    - files: /var/db/locate.database
      skip: true

- name: setting osx system preferences
  osx_defaults: >
    domain={{ item.domain }}
    key={{ item.key }}
    type={{ item.type }}
    value={{ item.value }}
    array_add={{ item.array_add | default('false') }}
  with_items: "{{ osx_setting }}"
  notify: apply setting
  changed_when: true

